// config.js
const CONFIG = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 400,
    GRAVITY: 0.8,
    GAME_SPEED: 5,
    UNICORN_WIDTH: 94,
    UNICORN_HEIGHT: 64,
    UNICORN_START_X: 100,
    UNICORN_START_Y: 300,
    PLATFORM_HEIGHT: 50,
    SPRITE_PATH: 'unicorn.png',
    LASER_SPEED: 10,
    LASER_WIDTH: 20,
    LASER_HEIGHT: 5,
    LASER_COLOR: 'red',
    OBSTACLE_HIT_POINTS: 3,
    EXPLOSION_PARTICLES: 20,
    EXPLOSION_PARTICLE_SIZE: 5,
    EXPLOSION_PARTICLE_SPEED: 3
};